<?php
/** @var Magento\Framework\View\Template $block */
?>
<div class="blog-post-list">
    <h1><?= __('Blog post list') ?></h1>
    <ul>
        <li><a href="<?= $block->getUrl('blog/post/detail', ['id' => 1]) ?>"> Post 1</a></li>
        <li><a href="<?= $block->getUrl('blog/post/detail', ['id' => 2]) ?>"> Post 2</a></li>
        <li><a href="<?= $block->getUrl('blog/post/detail', ['id' => 3]) ?>"> Post 3</a></li>
    </ul>
    <p><?= __('Post count: %1', 3) ?></p>
</div>